galaxy_info:
  author: Sam Doran
  description: Install and configure MongoDB
  company: Ansible by Red Hat
  license: MIT
  min_ansible_version: 2.3

  platforms:
  - name: EL
    versions:
      - 7

  galaxy_tags:
    - database
    - mongo
    - mongodb

dependencies: []
